name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.13.1
  geolocator: ^11.1.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  permission_handler: ^11.4.0
  shared_preferences: ^2.2.3
  uuid: ^4.5.1
  firebase_database: ^11.1.0
  firebase_auth: ^5.7.0
  cloud_functions: ^5.6.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kmitl.png